name: campus_circle
description: 校园圈互动平台 - 连接校园生活的社交平台
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  # provider: ^6.1.1
  
  # 路由管理
  go_router: ^10.1.2
  
  # 网络请求
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # 移除mysql1依赖 - 不支持Flutter Web
  # mysql1: ^0.20.0
  
  # JSON序列化
  json_annotation: ^4.9.0
  
  # UI组件
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.2.4
  
  # 工具库
  intl: ^0.18.1
  uuid: ^4.1.0
  crypto: ^3.0.3
  
  # 其他功能
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # 代码生成
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/
    
  # fonts:
  #   - family: PingFang
  #     fonts:
  #       - asset: assets/fonts/PingFang-Regular.ttf
  #       - asset: assets/fonts/PingFang-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/PingFang-Bold.ttf
  #         weight: 700